# ------------------------Spring------------------------------
spring:
    profiles:
        active: dev
    thymeleaf:
        cache: false
        mode: HTML5
    http:
        multipart:
            max-file-size: 5MB
    messages:
        basename: ValidationMessages
        encoding: UTF-8
# ------------------------Mybatis------------------------------
mybatis:
    type-aliases-package: com.groundinc.entity
# ------------------------Authorization------------------------------
jwt:
  header: Authorization
  tokenHead: "Bearer "