# ------------------------Datasource------------------------------
app:
  datasource:
    ground:
      jdbc-url: jdbc:mysql://localhost:3306/hors?characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      testOnBorrow: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 3600000
# ------------------------tomcat------------------------------
server:
  servlet:
    context-path: /v1
  portNum: 8090
# ------------------------logging------------------------------
logging:
  config: classpath:config/logback-ground.xml
# ------------------------InitialPassword------------------------------
pwd:
  password: 123456